import { useState } from 'react';
import { useSnackbar } from 'notistack';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import InputAdornment from '@mui/material/InputAdornment';
import MenuItem from '@mui/material/MenuItem';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import Chip from '@mui/material/Chip';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import { FilterBar } from '@/components/common/FilterBar';
import { DataTable, type ColumnDef } from '@/components/common/DataTable';
import { ConfirmDialog } from '@/components/common/ConfirmDialog';
import { ErrorState } from '@/components/common/ErrorState';
import { ReportFormDialog } from './ReportFormDialog';
import { useCreateReportMutation, useDeleteReportMutation, useListReportsQuery } from '@/features/reports/reportsApi';
import type { ReportItem, ReportStatus } from '@/features/reports/types';
import { formatDateTime } from '@/utils/formatters';
import type { ReportRequestFormValues } from '@/utils/validation';

const STATUS_COLOR: Record<ReportStatus, 'success' | 'warning' | 'error'> = {
  ready: 'success',
  processing: 'warning',
  failed: 'error',
};

/** Ad-hoc, saved/generated report jobs (a title + site set + date range +
 *  format, queued and downloaded later) - distinct from the always-live
 *  Tower Risk Reports tab, which reflects current conditions. */
export function SavedReportsTab() {
  const { enqueueSnackbar } = useSnackbar();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [formOpen, setFormOpen] = useState(false);
  const [pendingDelete, setPendingDelete] = useState<ReportItem | null>(null);

  const { data, isLoading, isError, refetch } = useListReportsQuery({
    search: search || undefined,
    status: (status as ReportStatus) || undefined,
    page,
    pageSize,
  });
  const [createReport, { isLoading: creating }] = useCreateReportMutation();
  const [deleteReport, { isLoading: deleting }] = useDeleteReportMutation();

  const handleCreate = async (values: ReportRequestFormValues) => {
    try {
      await createReport(values).unwrap();
      setFormOpen(false);
      enqueueSnackbar('Report generation started', { variant: 'success' });
    } catch {
      enqueueSnackbar('Failed to create report', { variant: 'error' });
    }
  };

  const handleDownload = (report: ReportItem) => {
    if (report.status !== 'ready') {
      enqueueSnackbar('Report is not ready for download yet', { variant: 'warning' });
      return;
    }
    if (report.format === 'csv') {
      const header = 'title,sites,dateFrom,dateTo,format\n';
      const line = `${report.title},"${report.siteNames.join('; ')}",${report.dateFrom},${report.dateTo},${report.format}`;
      const blob = new Blob([header + line], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${report.title.replace(/\s+/g, '_')}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } else {
      enqueueSnackbar(`In production this downloads ${report.title} (${report.format.toUpperCase()}) from the backend`, {
        variant: 'info',
      });
    }
  };

  const handleConfirmDelete = async () => {
    if (!pendingDelete) return;
    try {
      await deleteReport(pendingDelete.id).unwrap();
      enqueueSnackbar('Report deleted', { variant: 'success' });
    } catch {
      enqueueSnackbar('Failed to delete report', { variant: 'error' });
    } finally {
      setPendingDelete(null);
    }
  };

  const columns: ColumnDef<ReportItem>[] = [
    { key: 'title', header: 'Title', sortable: false },
    { key: 'siteNames', header: 'Sites', render: (r) => (r.siteNames.length > 2 ? `${r.siteNames.slice(0, 2).join(', ')} +${r.siteNames.length - 2}` : r.siteNames.join(', ')) },
    { key: 'range', header: 'Date Range', render: (r) => `${r.dateFrom} → ${r.dateTo}` },
    { key: 'format', header: 'Format', render: (r) => r.format.toUpperCase() },
    { key: 'status', header: 'Status', render: (r) => <Chip size="small" label={r.status} color={STATUS_COLOR[r.status]} sx={{ textTransform: 'capitalize' }} /> },
    { key: 'generatedBy', header: 'Generated By' },
    { key: 'generatedAt', header: 'Generated At', render: (r) => formatDateTime(r.generatedAt) },
    {
      key: 'actions',
      header: '',
      align: 'right',
      render: (r) => (
        <Stack direction="row" spacing={0.5} justifyContent="flex-end">
          <Tooltip title="Download">
            <span>
              <IconButton size="small" onClick={() => handleDownload(r)} disabled={r.status !== 'ready'}>
                <DownloadRoundedIcon fontSize="small" />
              </IconButton>
            </span>
          </Tooltip>
          <Tooltip title="Delete">
            <IconButton size="small" onClick={() => setPendingDelete(r)}>
              <DeleteOutlineRoundedIcon fontSize="small" color="error" />
            </IconButton>
          </Tooltip>
        </Stack>
      ),
    },
  ];

  return (
    <Stack spacing={2}>
      <Stack direction="row" justifyContent="flex-end">
        <Button startIcon={<AddRoundedIcon />} variant="contained" onClick={() => setFormOpen(true)}>
          New Report
        </Button>
      </Stack>

      <FilterBar>
        <TextField
          size="small"
          placeholder="Search reports..."
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
            setPage(1);
          }}
          sx={{ minWidth: 240 }}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <SearchRoundedIcon fontSize="small" />
              </InputAdornment>
            ),
          }}
        />
        <TextField
          select
          size="small"
          label="Status"
          value={status}
          onChange={(e) => {
            setStatus(e.target.value);
            setPage(1);
          }}
          sx={{ minWidth: 160 }}
        >
          <MenuItem value="">All statuses</MenuItem>
          <MenuItem value="ready">Ready</MenuItem>
          <MenuItem value="processing">Processing</MenuItem>
          <MenuItem value="failed">Failed</MenuItem>
        </TextField>
      </FilterBar>

      {isError ? (
        <ErrorState onRetry={refetch} />
      ) : (
        <DataTable
          columns={columns}
          rows={data?.items ?? []}
          getRowId={(r) => r.id}
          total={data?.total ?? 0}
          page={page}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={(size) => {
            setPageSize(size);
            setPage(1);
          }}
          loading={isLoading}
          emptyMessage="No reports match the selected filters."
        />
      )}

      <ReportFormDialog open={formOpen} submitting={creating} onClose={() => setFormOpen(false)} onSubmit={handleCreate} />

      <ConfirmDialog
        open={Boolean(pendingDelete)}
        title="Delete report?"
        message={`This will permanently delete "${pendingDelete?.title}". This action cannot be undone.`}
        confirmLabel="Delete"
        destructive
        loading={deleting}
        onConfirm={handleConfirmDelete}
        onCancel={() => setPendingDelete(null)}
      />
    </Stack>
  );
}
